CREATE BITMAP INDEX idx_aid_au --8 Blocks
ON AIRCRAFTUTILIZATION(AIRCRAFTID);

CREATE BITMAP INDEX idx_aid_lr --16 blocks
ON LOGBOOKREPORTING(AIRCRAFTID);

CREATE BITMAP INDEX idx_pid_lr --16 blocks
ON LOGBOOKREPORTING(PERSONID);
 
SELECT * FROM USER_INDEXES

--After Creating Indexes
--With view
--1)Cost is 3048
SELECT F.MONTHID, SUM(F.FLIGHTHOURS) AS FH, SUM(F.FLIGHTCYCLES) AS FC
FROM FACTS_DRILLACCROSS F, AIRCRAFTDIMENSION A
WHERE F.AIRCRAFTID = A.ID AND A.MODEL = '777'
GROUP BY F.MONTHID;

--2)Cost is 440
SELECT SUM(F.SCHEDULEDOUTOFSERVICE) AS ADOSS, 
       SUM(F.UNSCHEDULEDOUTOFSERVICE) AS ADOSU
FROM FACTS_DRILLACCROSS F, MONTHS M
WHERE F.AIRCRAFTID = 'XY-WTR' AND M.ID = F.MONTHID
GROUP BY M.Y;

--3)Cost is 3048
SELECT 1000*SUM(F.COUNTER)/SUM(F.FLIGHTHOURS) as RRh,
       100*SUM(F.COUNTER)/SUM(F.FLIGHTCYCLES) as RRc,
       1000*SUM(F.PIREP)/SUM(F.FLIGHTHOURS) as PRRh,
       100*SUM(F.PIREP)/SUM(F.FLIGHTCYCLES) as PRRc,
       1000*SUM(F.MAREP)/SUM(F.FLIGHTHOURS) as MRRh,
       100*SUM(F.MAREP)/SUM(F.FLIGHTCYCLES) as MRRc
FROM FACTS_DRILLACCROSS F, AIRCRAFTDIMENSION A
WHERE F.AIRCRAFTID = A.ID AND A.MODEL = '777'
GROUP BY F.MONTHID;

--4)Cost is 2061
SELECT 1000*SUM(F.MAREP)/SUM(F.FLIGHTHOURS) as MRRh,
       100*SUM(F.MAREP)/SUM(F.FLIGHTCYCLES) as MRRc
FROM FACTS_DRILLACCROSS F, AIRCRAFTDIMENSION A, PEOPLEDIMENSION P
WHERE F.AIRCRAFTID = A.ID AND P.ID = F.PERSONID AND P.AIRPORT = 'KRS'
GROUP BY A.MODEL;


--Without views
--1)Cost is 388
SELECT T.MONTHID, SUM(AU.FLIGHTHOURS) AS FH, SUM(AU.FLIGHTCYCLES) AS FC
FROM TEMPORALDIMENSION T, AIRCRAFTDIMENSION AD, AIRCRAFTUTILIZATION AU
WHERE AU.AIRCRAFTID = AD.ID AND AU.TIMEID = T.ID AND AD.MODEL = '777'
GROUP BY T.MONTHID;

--2)Cost is 141
SELECT SUM(AU.SCHEDULEDOUTOFSERVICE) AS ADOSS, 
       SUM(AU.UNSCHEDULEDOUTOFSERVICE) AS ADOSU
FROM AIRCRAFTUTILIZATION AU, MONTHS M, TEMPORALDIMENSION T
WHERE AU.AIRCRAFTID = 'XY-WTR' AND M.ID = T.MONTHID AND AU.TIMEID = T.ID
GROUP BY M.Y;

--3)Cost is 1283
SELECT LR.MONTHID,
       1000*(MAREP+PIREP)/FH AS RRh,
       100*(MAREP+PIREP)/FC AS RRc,
       1000*PIREP/FH AS PRRh,
       100*PIREP/FC AS PRRc,
       1000*MAREP/FH AS MRRh,
       100*MAREP/FC AS MRRc      
FROM (SELECT T.MONTHID, SUM(AU.FLIGHTHOURS) AS FH, SUM(AU.FLIGHTCYCLES) AS FC
      FROM TEMPORALDIMENSION T, AIRCRAFTDIMENSION AD, AIRCRAFTUTILIZATION AU
      WHERE AU.AIRCRAFTID = AD.ID AND AU.TIMEID = T.ID AND AD.MODEL = '777'
      GROUP BY T.MONTHID) AU,     
      (SELECT L.MONTHID,
              SUM(CASE WHEN P.ROLE ='M' THEN L.COUNTER ELSE 0 END) AS MAREP,
              SUM(CASE WHEN P.ROLE ='P' THEN L.COUNTER ELSE 0 END) AS PIREP
       FROM LOGBOOKREPORTING L, AIRCRAFTDIMENSION AD, PEOPLEDIMENSION P
       WHERE L.AIRCRAFTID = AD.ID AND P.ID = L.PERSONID AND AD.MODEL = '777'
       GROUP BY L.MONTHID
      ) LR  
WHERE AU.MONTHID = LR.MONTHID;


--4)Cost is 760
SELECT LR.MODEL,1000*MAREP/FH AS MRRh, 100*MAREP/FC AS MRRc      
FROM (SELECT AD.MODEL,SUM(AU.FLIGHTHOURS) AS FH, SUM(AU.FLIGHTCYCLES) AS FC
      FROM AIRCRAFTDIMENSION AD, AIRCRAFTUTILIZATION AU
      WHERE AU.AIRCRAFTID = AD.ID 
      GROUP BY AD.MODEL) AU,
      
      (SELECT AD.MODEL,SUM(CASE WHEN P.ROLE ='M' THEN L.COUNTER ELSE 0 END) AS MAREP,
              SUM(CASE WHEN P.ROLE ='P' THEN L.COUNTER ELSE 0 END) AS PIREP
       FROM LOGBOOKREPORTING L, AIRCRAFTDIMENSION AD, PEOPLEDIMENSION P
       WHERE L.AIRCRAFTID = AD.ID AND P.AIRPORT = 'KRS' AND P.ID = L.PERSONID
       GROUP BY AD.MODEL
      ) LR  
WHERE AU.MODEL = LR.MODEL;




