--Without Indexes
--With view
--1)Cost is 3048
SELECT F.MONTHID, SUM(F.FLIGHTHOURS) AS FH, SUM(F.FLIGHTCYCLES) AS FC
FROM FACTS_DRILLACCROSS F, AIRCRAFTDIMENSION A
WHERE F.AIRCRAFTID = A.ID AND A.MODEL = 'A340'
GROUP BY F.MONTHID;

--2)Cost is 1761
SELECT SUM(F.SCHEDULEDOUTOFSERVICE) AS ADOSS, 
       SUM(F.UNSCHEDULEDOUTOFSERVICE) AS ADOSU
FROM FACTS_DRILLACCROSS F, MONTHS M
WHERE F.AIRCRAFTID = 'XY-WTR' AND M.ID = F.MONTHID
GROUP BY M.Y;

--3)Cost is 3048
SELECT 1000*SUM(F.COUNTER)/SUM(F.FLIGHTHOURS) as RRh,
       100*SUM(F.COUNTER)/SUM(F.FLIGHTCYCLES) as RRc,
       1000*SUM(F.PIREP)/SUM(F.FLIGHTHOURS) as PRRh,
       100*SUM(F.PIREP)/SUM(F.FLIGHTCYCLES) as PRRc,
       1000*SUM(F.MAREP)/SUM(F.FLIGHTHOURS) as MRRh,
       100*SUM(F.MAREP)/SUM(F.FLIGHTCYCLES) as MRRc
FROM FACTS_DRILLACCROSS F, AIRCRAFTDIMENSION A
WHERE F.AIRCRAFTID = A.ID AND A.MODEL = 'A340'
GROUP BY F.MONTHID;

--4)Cost is 3049
SELECT 1000*SUM(F.MAREP)/SUM(F.FLIGHTHOURS) as MRRh,
       100*SUM(F.MAREP)/SUM(F.FLIGHTCYCLES) as MRRc
FROM FACTS_DRILLACCROSS F, AIRCRAFTDIMENSION A, PEOPLEDIMENSION P
WHERE F.AIRCRAFTID = A.ID AND P.ID = F.PERSONID AND P.AIRPORT = 'CIA'
GROUP BY A.MODEL;


--Without views and indexes
--1)Cost is 1744
SELECT L.MONTHID, SUM(AU.FLIGHTHOURS) AS FH, SUM(AU.FLIGHTCYCLES) AS FC
FROM LOGBOOKREPORTING L, AIRCRAFTDIMENSION AD, AIRCRAFTUTILIZATION AU
WHERE AU.AIRCRAFTID = AD.ID AND L.AIRCRAFTID = AD.ID AND AD.MODEL = 'A340'
GROUP BY L.MONTHID;

--2)Cost is 526
SELECT SUM(AU.SCHEDULEDOUTOFSERVICE) AS ADOSS, 
       SUM(AU.UNSCHEDULEDOUTOFSERVICE) AS ADOSU
FROM AIRCRAFTUTILIZATION AU, MONTHS M, TEMPORALDIMENSION T
WHERE AU.AIRCRAFTID = 'XY-WTR' AND M.ID = T.MONTHID AND AU.TIMEID = T.ID
GROUP BY M.Y;

--3)Cost is 8961
SELECT 1000*SUM(L.COUNTER)/SUM(AU.FLIGHTHOURS) AS RRh,
       100*SUM(L.COUNTER)/SUM(AU.FLIGHTCYCLES) AS RRc,
       1000*SUM(CASE WHEN P.ROLE ='P' THEN L.COUNTER ELSE 0 END)/SUM(AU.FLIGHTHOURS) AS PRRh,
       100*SUM(CASE WHEN P.ROLE ='P' THEN L.COUNTER ELSE 0 END)/SUM(AU.FLIGHTCYCLES) AS PRRc,
       1000*SUM(CASE WHEN P.ROLE ='M' THEN L.COUNTER ELSE 0 END)/SUM(AU.FLIGHTHOURS) AS MRRh,
       100*SUM(CASE WHEN P.ROLE ='M' THEN L.COUNTER ELSE 0 END)/SUM(AU.FLIGHTCYCLES) AS MRRc
FROM LOGBOOKREPORTING WITH(INDEX(idx_mid)), AIRCRAFTDIMENSION AD, PEOPLEDIMENSION P, AIRCRAFTUTILIZATION AU
WHERE L.PERSONID = P.ID AND AU.AIRCRAFTID = AD.ID AND L.AIRCRAFTID = AD.ID AND AD.MODEL = 'A340' 
GROUP BY L.MONTHID;

--4)Cost is 2335
SELECT 1000*SUM(CASE WHEN P.ROLE ='M' THEN L.COUNTER ELSE 0 END)/SUM(AU.FLIGHTHOURS) AS MRRh,
       100*SUM(CASE WHEN P.ROLE ='M' THEN L.COUNTER ELSE 0 END)/SUM(AU.FLIGHTCYCLES) AS MRRc
FROM  AIRCRAFTDIMENSION AD, PEOPLEDIMENSION P, AIRCRAFTUTILIZATION AU, LOGBOOKREPORTING L
WHERE AU.AIRCRAFTID = AD.ID AND L.AIRCRAFTID = AD.ID AND P.ID = L.PERSONID AND P.AIRPORT = 'CIA'
GROUP BY AD.MODEL;
